### ISSUE TITLE
Can you send me the Python code for chinese2digits

### ISSUE THREAD

**Issue by qingkongbandao** [Wall-ee/chinese2digits#1]
Can you send me the Python code for chinese2digits

**Comment by jiahuigeng** [comment]
Can you send me the Python code for chinese2digits

**Comment by yifeiluo1989** [comment]
Can you send me the Python code for chinese2digits

**Comment by Wall-ee** [comment]
> Can you send me the Python code for chinese2digits

I've just made a commit with python solution

**Comment by Wall-ee** [comment]
> Can you send me the Python code for chinese2digits



> Can you send me the Python code for chinese2digits

I've just made a commit with python solution
