### ISSUE TITLE
无法识别带有小数点的digits+chinese混合情况

### ISSUE THREAD

**Issue by eitbar** [Wall-ee/chinese2digits#14]
例如

`result = c2d.takeNumberFromString("33.5万")`

结果为

`{'inputText': '33.5万', 'replacedText': '33.5', 'CHNumberStringList': ['33.5万'], 'digitsStringList': ['33.5'], 'errorWordList': [], 'errorMsgList': []}`

**Comment by Wall-ee** [comment]
已修复，更新一下pip包即可
