### ISSUE TITLE
有关checkChinsesNubmerReasonable函数的问题

### ISSUE THREAD

**Issue by QvQQ** [Wall-ee/chinese2digits#15]
请问如下图所示的结果是预料中的正确情况吗？针对这样无意义的字符串有好的解决方法吗
![image](https://user-images.githubusercontent.com/35735975/106797903-311d5480-6698-11eb-8b2d-881d040fa656.png)

**Comment by Wall-ee** [comment]
我查一查 看看怎么解决

**Comment by Wall-ee** [comment]
这个问题已解决  切分问题， 不过 无意义+一个字符这个问题 已经在切分层面处理， 即只把有意义的数字提取出来
