### ISSUE TITLE
一些不合理case反馈

### ISSUE THREAD

**Issue by lai-bluejay** [Wall-ee/chinese2digits#16]
假设我有一个标准的文本：
```
明天见 我的车牌号是7G02D 白色的INSPIRE
```
如果使用：takeChineseNumberFromString，这个方法，会先提取文本中的数字，转成中文。
```
CHNumberStringListTemp = takingChineseDigitsMixRERules.findall(convertedCHString)
['7', '02']
['七', '零二']
```
会被转换成
```
[('02', '2', 2), ('7', '7', 1)]
```
最终转换的结果变成，

```
明天见 我的车牌号是7G2D 白色的INSPIRE 
```

你看看这块要不要加一个判断，如果是**字母和数字共同出现，不需要转换**。如果是\d+[wk]，可以转换

```
convertedCHString = traditionalTextConvertFunc(chText,traditionalConvert)
    """
    字符串 汉字数字字符串切割提取
    正则表达式方法
    """
    # TODO  check digits-alphabet-mixed， skip
    
    CHNumberStringListTemp = takingChineseDigitsMixRERules.findall(convertedCHString)
    print(CHNumberStringListTemp)
    #检查是不是  分之 切割不完整问题
    CHNumberStringListTemp = checkNumberSeg(CHNumberStringListTemp,convertedCHString)
    print(CHNumberStringListTemp)
    #检查末位是不是正负号
    CHNumberStringListTemp = checkSignSeg(CHNumberStringListTemp)
    print(CHNumberStringListTemp)
    #备份一个原始的提取，后期处结果的时候显示用
    OriginCHNumberTake = CHNumberStringListTemp.copy()
```

**还是说建议自己在使用前做好替换，跳过转换，而不是交给这个包做决策**

**Comment by lai-bluejay** [comment]
倒是改好了，你看看要不要把这类数据的判断加到代码里面吧，或者有使用者自己判断

```
['唉呀我今天开的不是粤', ' 白色 而是另外一辆 粤', ' '] ['R27Y58', 'A653PG']
['唉呀我今天开的不是粤', 'R27Y58', ' 白色 而是另外1辆 粤', 'A653PG', ' ']
唉呀我今天开的不是粤R27Y58 白色 而是另外一辆 粤A653PG 
```

**Comment by Wall-ee** [comment]
> 倒是改好了，你看看要不要把这类数据的判断加到代码里面吧，或者有使用者自己判断
> 
> ```
> ['唉呀我今天开的不是粤', ' 白色 而是另外一辆 粤', ' '] ['R27Y58', 'A653PG']
> ['唉呀我今天开的不是粤', 'R27Y58', ' 白色 而是另外1辆 粤', 'A653PG', ' ']
> 唉呀我今天开的不是粤R27Y58 白色 而是另外一辆 粤A653PG 
> ```

啊 这个太难处理了， 我琢磨琢磨要不要加个判断

**Comment by Wall-ee** [comment]
> 倒是改好了，你看看要不要把这类数据的判断加到代码里面吧，或者有使用者自己判断
> 
> ```
> ['唉呀我今天开的不是粤', ' 白色 而是另外一辆 粤', ' '] ['R27Y58', 'A653PG']
> ['唉呀我今天开的不是粤', 'R27Y58', ' 白色 而是另外1辆 粤', 'A653PG', ' ']
> 唉呀我今天开的不是粤R27Y58 白色 而是另外一辆 粤A653PG 
> ```

混合提取的规则已经升级了
