### ISSUE TITLE
无法导入chinese2digits.c2d，应该怎样解决？

### ISSUE THREAD

**Issue by NamelessUzer** [Wall-ee/chinese2digits#18]
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from chinese2digits import c2d
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ac7f87462595> in <module>
----> 1 from chinese2digits import c2d

ImportError: cannot import name 'c2d' from 'chinese2digits' (c:\python\lib\site-packages\chinese2digits\__init__.py)

**Comment by Wall-ee** [comment]
额 包名错误……
