### ISSUE TITLE
小数部分的转换有bug

### ISSUE THREAD

**Issue by thunder-sword** [Wall-ee/chinese2digits#19]
放截图：
![image](https://user-images.githubusercontent.com/64960284/134793186-bc44f594-3d30-48ea-a69e-36dfb9951892.png)
点后面前几位如果都是零的话将不会处理，猜测应该是不小心将小数部分的匹配和整数部分的匹配一样了，导致开头的零被省略。

**Comment by Wall-ee** [comment]
> 放截图： ![image](https://user-images.githubusercontent.com/64960284/134793186-bc44f594-3d30-48ea-a69e-36dfb9951892.png) 点后面前几位如果都是零的话将不会处理，猜测应该是不小心将小数部分的匹配和整数部分的匹配一样了，导致开头的零被省略。

最新版本已修复
