### ISSUE TITLE
繁体字转换拾时有bug

### ISSUE THREAD

**Issue by thunder-sword** [Wall-ee/chinese2digits#21]
放截图：
![image](https://user-images.githubusercontent.com/64960284/134796978-7df0ac0b-ff11-474b-bcb4-9248c113d757.png)
这个报错了，感觉可能是因为将拾转换只是当作了一个数值计量单位，并没有处理只有一个它的时候的情况，感觉这里的繁体字替换可能太灵活了，不知道在转换前直接一对一将繁体字直接转换为简体字再处理可不可行。
略述愚见，如果不正确，还请见谅。

**Comment by Wall-ee** [comment]
最新版本已处理
