### ISSUE TITLE
takeNumberFromString('百/千/万/百万/千万')

### ISSUE THREAD

**Issue by onebula** [Wall-ee/chinese2digits#22]
{'inputText': '百/千/万/百万/千万',
 'replacedText': '百/千/万/百万/千万',
 'CHNumberStringList': [],
 'digitsStringList': [],
 'errorWordList': [],
 'errorMsgList': []}

提取出来100/1000/10000/1000000/10000000更好吧？

**Comment by Wall-ee** [comment]
> {'inputText': '百/千/万/百万/千万', 'replacedText': '百/千/万/百万/千万', 'CHNumberStringList': [], 'digitsStringList': [], 'errorWordList': [], 'errorMsgList': []}
> 
> 提取出来100/1000/10000/1000000/10000000更好吧？

这个暂时不考虑，如果有成语百战百胜，这种就比较麻烦了，单位这个方面还是加上 一百 一万 再转比较好
