### ISSUE TITLE
BUG: 【一百03】 识别错误

### ISSUE THREAD

**Issue by redreamality** [Wall-ee/chinese2digits#23]
一百03： 识别错误

识别结果：
10003

期望结果：
103

**Comment by Wall-ee** [comment]
我看看这个， 不过为啥会有这种汉字不汉子  阿拉伯数字不阿拉伯数字的 情况？！？！哪一家的asr？

**Comment by Wall-ee** [comment]
我看了一下 这个没问题，原始记录是切开成  100   03  的。  程序逻辑就是这样， 汉字大单位+阿拉伯数字，必然是按照2个数字切开进行识别和转换。 这个是符合汉语言逻辑的。  如果想统一，那就在传入数据前全部变成汉字或者数字
