### ISSUE TITLE
字典BUG

### ISSUE THREAD

**Issue by wufan-nlper** [Wall-ee/chinese2digits#25]
代码：
import chinese2digits as c2d
q = "一兆韦德"
q = c2d.takeChineseNumberFromString(q)["replacedText"]

会报错：
File "/Users/chinese2digits.py", line 64, in coreCHToDigits
    if val >= 10 and i == 0:  #应对 十三 十四 十*之类，说明为十以上的数字，看是不是十三这种
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

似乎是因为识别到了一兆但是字典common_used_ch_numerals中没有转换兆的key，希望尽快修改

**Comment by Wall-ee** [comment]
好 我看看

**Comment by Wall-ee** [comment]
已处理   将  兆 去除
