### ISSUE TITLE
特殊字符『〇』识别错误

### ISSUE THREAD

**Issue by MarinYoung4596** [Wall-ee/chinese2digits#26]
输入： 国家主席发表二〇二三年新年贺词

期望输出：国家主席发表2023年新年贺词

实际输出：{'inputText': '国家主席发表二〇二三年新年贺词', 'replacedText': '国家主席发表2〇23年新年贺词', 'CHNumberStringList': ['二', '二三'], 'digitsStringList': ['2', '23'], 'errorWordList': [], 'errorMsgList': []}

**Comment by Wall-ee** [comment]
卧槽~~~这是谁的ASR结果？~~~为啥用这个〇~~………………

**Comment by cgisky1980** [comment]
> 卧槽~~~这是谁的ASR结果？~~~为啥用这个〇~~………………

互转功能做好了吗？

**Comment by cgisky1980** [comment]
> 输入： 国家主席发表二〇二三年新年贺词
> 
> 期望输出：国家主席发表2023年新年贺词
> 
> 实际输出：{'inputText': '国家主席发表二〇二三年新年贺词', 'replacedText': '国家主席发表2〇23年新年贺词', 'CHNumberStringList': ['二', '二三'], 'digitsStringList': ['2', '23'], 'errorWordList': [], 'errorMsgList': []}

前置处理下把〇替换成零

**Comment by Wall-ee** [comment]
> 输入： 国家主席发表二〇二三年新年贺词
> 
> 期望输出：国家主席发表2023年新年贺词
> 
> 实际输出：{'inputText': '国家主席发表二〇二三年新年贺词', 'replacedText': '国家主席发表2〇23年新年贺词', 'CHNumberStringList': ['二', '二三'], 'digitsStringList': ['2', '23'], 'errorWordList': [], 'errorMsgList': []}

已处理  二〇二三 可识别为 2023
