### ISSUE TITLE
阿拉伯和中文混合的情况识别问题：”5万3“、”六千7“

### ISSUE THREAD

**Issue by hxxxxh** [Wall-ee/chinese2digits#27]
阿拉伯和中文混合的情况识别问题：
”5万3“ 识别成了 ['50000', '3']，实际上想要的是 53000
”六千7“ 识别成了 ['6000', '7']，实际上想要的是 6700

但是有时候也能出来想要的结果：

'6千七' 识别成 6700

感觉有点不一致，这种情况是如何控制的呢？

**Comment by Wall-ee** [comment]
这个需要把前后的上下文拿出来，我看一看。 我这边会根据前后上下文来校对这种口语化的表达，你发我一下上下文

**Comment by Wall-ee** [comment]
啊 我知道了， 就是你的表述问题，  如果希望可以转化 你先把阿拉伯数字变成汉字。  我这边汉字和阿拉伯数字会独立对待。 要么五万三 ，  要么就是分开的 5万     3   这样子拆分词语
