### ISSUE TITLE
bugs report

### ISSUE THREAD

**Issue by HectorShao** [Wall-ee/chinese2digits#4]
issues with some abbreviated statements
- [ ] takeChineseNumberFromString('二千十七')--> 2007
  should be 2017
- [ ] takeChineseNumberFromString('二千七')--> 2007
  should be 2700
- [ ] takeChineseNumberFromString('两千') --> None
  should be 2000

**Comment by Wall-ee** [comment]
第一条和第二条之前考虑处理过，但是，由于是非标准表述，和标准表述的算法容易有冲突，还在考虑新的算法。
第三点问题，我正准备把这个部分和大写转小写 放在一起解决， 最近会有版本更新

**Comment by Wall-ee** [comment]
> issues with some abbreviated statements
> 
>  [*]  takeChineseNumberFromString('二千十七')--> 2017
>   should be 2017
>  [*]  takeChineseNumberFromString('二千七')--> 2700
>   should be 2700
>  [*]  takeChineseNumberFromString('两千') --> 2000
>   should be 2000

All problem has been solved. 
所有问题均已解决

重新打包了一下 可以试一下
I've repacked and try this:
pip install -i https://pypi.python.org/pypi chinese2digits==1.1.5
或
or
pip install chinese2digits==1.1.5
