### ISSUE TITLE
无法识别300万

### ISSUE THREAD

**Issue by HectorShao** [Wall-ee/chinese2digits#5]
digits+chinese混合的情况还是挺常见的，这种数字暂时还不能识别。

**Comment by Wall-ee** [comment]
> digits+chinese混合的情况还是挺常见的，这种数字暂时还不能识别。

额 这个是哪门子的鬼产品？哈哈哈 我patch 一个版本吧~~~几个大厂的ASR部门我都聊过，让他们要么全中文，要么全数字，这混搭的什么鬼？  最近我patch一个版本吧~

**Comment by HectorShao** [comment]
手机端讯飞的语音输入法是这样的，说`300万`出来的真是`300+万`，这种大颗粒度如果加很多零也确实挺凶残的，哈哈

**Comment by Wall-ee** [comment]
> 手机端讯飞的语音输入法是这样的，说`300万`出来的真是`300+万`，这种大颗粒度如果加很多零也确实挺凶残的，哈哈

是的  但是他的嵌入式的sdk 我是提过意见的 让他们都改成纯文字，手机端的sdk还是要有取舍，哎，patch一个版本吧~

**Comment by Wall-ee** [comment]
> 手机端讯飞的语音输入法是这样的，说`300万`出来的真是`300+万`，这种大颗粒度如果加很多零也确实挺凶残的，哈哈

更新了一版，新增了一个方法，并且可以混合识别了，可以看下readme， pip 升级一下包就ok了
