### ISSUE TITLE
那个字符串转int 函数有问题

### ISSUE THREAD

**Issue by fengmangseo** [Wall-ee/chinese2digits#6]
个位会追加1 你循环个10w 试试大部分都对不上 个位个位会追加1 
百位数 会增加十位
输入 中文 十万 直接返回一个 0
你看看这个包
[https://github.com/pkumza/numcn](https://github.com/pkumza/numcn)

**Comment by Wall-ee** [comment]
> 个位会追加1 你循环个10w 试试大部分都对不上 个位个位会追加1
> 百位数 会增加十位
> 输入 中文 十万 直接返回一个 0
> 你看看这个包
> https://github.com/pkumza/numcn

另外这个bug不是京都的问题，是一个非计数单位校验问题，已处理。
更新了一版，新增了一个方法，并且可以混合识别了，可以看下readme， pip 升级一下包就ok了
