### ISSUE TITLE
有内存泄露的问题和一些BUG

### ISSUE THREAD

**Issue by SCAUapc** [Wall-ee/chinese2digits#8]
您好！您的工具非常好用 ,但是我在用的时候会出现内存泄露（一直往上涨）的问题。另一方面，如果出现“X（中文）分之X（阿拉伯）（如十分之3，百分之3）”会报错，代码会报错来着...

**Comment by Wall-ee** [comment]
我检查一下 
1   麻烦详细描述一下在什么系统环境会有这个问题？因为我这套工具基本上部署成服务以后一年都不怎么管，没出过这种溢出问题   

2  中文阿拉伯混合的报错信息发一下，入参和报错信息

**Comment by SCAUapc** [comment]
InvalidOperation                          Traceback (most recent call last)
<ipython-input-115-e06ae7c3f942> in <module>
----> 1 c2d.takeNumberFromString(test_content)['CHNumberStringList']

d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in takeNumberFromString(chText, simpilfy, percentConvert, traditionalConvert, digitsNumberSwitch, *args, **kwargs)
    502     :return: Dict like result. 'inputText',replacedText','CHNumberStringList':CHNumberStringList,'digitsStringList'
    503     """
--> 504     finalResult = takeChineseNumberFromString(chText,simpilfy=simpilfy,percentConvert = percentConvert,traditionalConvert= traditionalConvert,digitsNumberSwitch= digitsNumberSwitch)
    505     return finalResult
    506 

d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in takeChineseNumberFromString(chText, simpilfy, percentConvert, traditionalConvert, digitsNumberSwitch, *args, **kwargs)
    469     replacedText = chText
    470     if CHNumberStringList.__len__()>0:
--> 471         digitsStringList = list(map(lambda x:chineseToDigits(x,simpilfy=simpilfy,percentConvert=percentConvert),CHNumberStringList))
    472         # # 用标准清洗后的字符串进行转换
    473         # digitsStringList = list(

d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in <lambda>(x)
    469     replacedText = chText
    470     if CHNumberStringList.__len__()>0:
--> 471         digitsStringList = list(map(lambda x:chineseToDigits(x,simpilfy=simpilfy,percentConvert=percentConvert),CHNumberStringList))
    472         # # 用标准清洗后的字符串进行转换
    473         # digitsStringList = list(

d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in chineseToDigits(chineseDigitsMixString, simpilfy, percentConvert)
    207         if percentConvert == True:
    208             if perCountingString == '%':
--> 209                 convertResult = float(Decimal(convertResult)/100)
    210             elif perCountingString == '‰':
    211                 convertResult = float(Decimal(convertResult)/1000)

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

> 我检查一下
> 1 麻烦详细描述一下在什么系统环境会有这个问题？因为我这套工具基本上部署成服务以后一年都不怎么管，没出过这种溢出问题
> 
> 2 中文阿拉伯混合的报错信息发一下，入参和报错信息

**Comment by SCAUapc** [comment]
> 我检查一下
> 1 麻烦详细描述一下在什么系统环境会有这个问题？因为我这套工具基本上部署成服务以后一年都不怎么管，没出过这种溢出问题
> 
> 2 中文阿拉伯混合的报错信息发一下，入参和报错信息

我这样子就会报错：
test_content = "汇中公司预期一天就是百分之10的逾期费没有商量的余地，希望政府人员，政府领导帮帮忙"
c2d.takeNumberFromString(test_content)['CHNumberStringList']

**Comment by SCAUapc** [comment]
> 我检查一下
> 1 麻烦详细描述一下在什么系统环境会有这个问题？因为我这套工具基本上部署成服务以后一年都不怎么管，没出过这种溢出问题
> 
> 2 中文阿拉伯混合的报错信息发一下，入参和报错信息

这是我这边的系统信息~4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
感谢你

**Comment by SCAUapc** [comment]
> 我检查一下
> 1 麻烦详细描述一下在什么系统环境会有这个问题？因为我这套工具基本上部署成服务以后一年都不怎么管，没出过这种溢出问题
> 
> 2 中文阿拉伯混合的报错信息发一下，入参和报错信息

而且有个很奇怪的现象...如果我用多进程去处理数据，处理数据过程里面有用您的这个工具。然后如果我开10个Pool，前5个都是正常的，第6哥开始就一直很慢很慢才有反应。（同时内存也一直在涨）不开多进程也有这个内存涨的情况发生。

**Comment by Wall-ee** [comment]
> InvalidOperation Traceback (most recent call last)
> in
> ----> 1 c2d.takeNumberFromString(test_content)['CHNumberStringList']
> 
> d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in takeNumberFromString(chText, simpilfy, percentConvert, traditionalConvert, digitsNumberSwitch, *args, **kwargs)
> 502 :return: Dict like result. 'inputText',replacedText','CHNumberStringList':CHNumberStringList,'digitsStringList'
> 503 """
> --> 504 finalResult = takeChineseNumberFromString(chText,simpilfy=simpilfy,percentConvert = percentConvert,traditionalConvert= traditionalConvert,digitsNumberSwitch= digitsNumberSwitch)
> 505 return finalResult
> 506
> 
> d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in takeChineseNumberFromString(chText, simpilfy, percentConvert, traditionalConvert, digitsNumberSwitch, *args, **kwargs)
> 469 replacedText = chText
> 470 if CHNumberStringList.**len**()>0:
> --> 471 digitsStringList = list(map(lambda x:chineseToDigits(x,simpilfy=simpilfy,percentConvert=percentConvert),CHNumberStringList))
> 472 # # 用标准清洗后的字符串进行转换
> 473 # digitsStringList = list(
> 
> d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in (x)
> 469 replacedText = chText
> 470 if CHNumberStringList.**len**()>0:
> --> 471 digitsStringList = list(map(lambda x:chineseToDigits(x,simpilfy=simpilfy,percentConvert=percentConvert),CHNumberStringList))
> 472 # # 用标准清洗后的字符串进行转换
> 473 # digitsStringList = list(
> 
> d:\Users\apc\AppData\Local\Continuum\anaconda3\lib\site-packages\chinese2digits\chinese2digits.py in chineseToDigits(chineseDigitsMixString, simpilfy, percentConvert)
> 207 if percentConvert == True:
> 208 if perCountingString == '%':
> --> 209 convertResult = float(Decimal(convertResult)/100)
> 210 elif perCountingString == '‰':
> 211 convertResult = float(Decimal(convertResult)/1000)
> 
> InvalidOperation: [<class 'decimal.ConversionSyntax'>]
> 
> > 我检查一下
> > 1 麻烦详细描述一下在什么系统环境会有这个问题？因为我这套工具基本上部署成服务以后一年都不怎么管，没出过这种溢出问题
> > 2 中文阿拉伯混合的报错信息发一下，入参和报错信息

百分之10 这个bug已修复~  内存溢出的问题还在测试，目前没发现，不过这个是哪家的asr生成的啊？这样混合………………
