### ISSUE TITLE
关于Go版本的异常处理问题

### ISSUE THREAD

**Issue by yucendulang** [Wall-ee/chinese2digits#9]
你好~
	floatResult, err := strconv.ParseFloat(convertResult, 32)
	if err != nil {
		panic(err)
       }

go版本这一段代码如果超出范围会稳定抛出panic

用户的输入不太好控制 这块是否可以改为返回err或者做出其他异常处理 

测试输入为:
10000000000000000000000000000000000000000000连

结果:
 panic: strconv.ParseFloat: parsing "10000000000000000000000000000000000000000000": value out of range

 github.com/Wall-ee/chinese2digits/chinese2digits.convertDigitsStringToFloat(0xc000028900, 0x2c, 0x2c)
1|main     |    /root/go/pkg/mod/github.com/!wall-ee/chinese2digits@v0.0.0-20200531124722-3da9c030a8a9/chinese2digits/chinese2digits.go:298 +0x283
1|main     | github.com/Wall-ee/chinese2digits/chinese2digits.ChineseToDigits(0xc000028900, 0x2c, 0x1, 0x832a80, 0x9688b0, 0x1, 0x1)
1|main     |    /root/go/pkg/mod/github.com/!wall-ee/chinese2digits@v0.0.0-20200531124722-3da9c030a8a9/chinese2digits/chinese2digits.go:336 +0xc6f
1|main     | github.com/Wall-ee/chinese2digits/chinese2digits.TakeChineseNumberFromString(0xc0000288d0, 0x2c, 0xc001c5f570, 0x4, 0x4, 0xc001c5f588, 0x4)
1|main     |    /root/go/pkg/mod/github.com/!wall-ee/chinese2digits@v0.0.0-20200531124722-3da9c030a8a9/chinese2digits/chinese2digits.go:793 +0x5d2
1|main     | github.com/Wall-ee/chinese2digits/chinese2digits.TakeNumberFromString(0xc0000288d0, 0x2c, 0x0, 0x0, 0x0, 0x2, 0x0)
1|main     |    /root/go/pkg/mod/github.com/!wall-ee/chinese2digits@v0.0.0-20200531124722-3da9c030a8a9/chinese2digits/chinese2digits.go:860 +0xff

**Comment by Wall-ee** [comment]
恩 我处理一下

**Comment by Wall-ee** [comment]
已处理好，如果还是出现尽量使用64位系统应该就没有问题了。
